@startuml

abstract class Controller {
  {abstract}-storage
  {abstract}-properties
  -paths
  +detections
  +start()
  +stop()
}

class MobileController {
  {static} -instance
  -MobileController()
  {static} +getInstance()
  +start()
  +stop()
}

class DesktopController {
  {static} -instance
  -DesktopController()
  {static} +getInstance()
  +start()
  +stop()
}

class DetectionsStorage {
   +save()
   +load()
}

class ObjectSeekerFactory {
   +getObjSeekers()
}

class PicSeekerFactory {
   +getPicSeekers()
}

class Detection {
  +path
  +descriptions
  +state
}

Controller *- Properties
Controller *- DetectionsStorage
Controller *- "0..*" Detection
Controller o..> Detections
Controller o..> "1..*" Seeker
Controller ..> ObjectSeekerFactory
Controller ..> PicSeekerFactory
Detection *- Detections
Seeker o..> "1" Detection
Seeker <|.. PicsSeeker

enum Detections {
   PROCESSING
   NO
   FOUND
   UNKNOWN
}

interface Seeker {
  {abstract} +find()
  {abstract} +stop()
}

interface PicsSeeker {
  {static}-picFormats
  {abstract} +find()
  {abstract} +stop()
}


Controller <|.. MobileController
Controller <|.. DesktopController
PicsSeeker <|.. DesktopFS
PicsSeeker <|.. MobileFS
PicsSeeker <|.. CloudFS
CloudService <|.. CloudFS

class DesktopFS {
   +find()
   +stop()
}

class MobileFS {
   +find()
   +stop()
}

class CloudFS {
   +find()
   +stop()
}


Seeker <|.. LandMarkSeeker
LandMarkSeeker <|.. GoogleObjSeeker
CloudService <|.. GoogleObjSeeker

interface LandMarkSeeker {
   {abstract} +find()
   {abstract} +stop()
}

class GoogleObjSeeker {
   +find()
   +stop()
}


interface CloudService {
  {abstract} +isConnected()
}

@enduml